name: Preview Deploy

on:
  workflow_run:
    workflows: ["Preview Build"]
    types:
      - completed

jobs:
  deploy:
    name: Website Deploy
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:

      - name: Download pr number
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: pr-number

      - name: Output pr number
        id: pr
        run: echo "::set-output name=id::$(<pr-number.txt)"

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: website-dist

      - name: Deploy Site
        run: |
          export PULL_REQUEST_NUMBER=$(<pr-number.txt)
          export DEPLOY_DOMAIN=https://preview-${PULL_REQUEST_NUMBER}-test-adaex.surge.sh
          echo "Deploy to $DEPLOY_DOMAIN"
          npx surge --project ./ --domain $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}

      - name: Deploy has failed
        if: ${{ failure() }}
        run: echo "failed"