# This workflow runs on target, so there is no need to worry about secrets
name: Website Preview Deploy

on:
  workflow_run:
    workflows: ['Website Preview']
    types: [completed]

jobs:
  # Build successfully, start deployment
  on-success:
    name: Build successfully
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download pr number
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: pr

      - name: Output pr number
        id: pr
        run: echo "::set-output name=id::$(<pr.txt)"

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: website

      - name: Deploy Site
        run: |
          echo "PULL_REQUEST_NUMBER is $PULL_REQUEST_NUMBER"
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ steps.pr.outputs.id }}

      - name: Deploy has succeeded
        if: ${{ success() }}
        run: |
          echo "PULL_REQUEST_NUMBER is $PULL_REQUEST_NUMBER"
        env:
          BOT_URL: ${{ secrets.BOT_URL }}
          PULL_REQUEST_NUMBER: ${{ steps.pr.outputs.id }}

      - name: Deploy has failed
        if: ${{ failure() }}
        run: |
          echo "PULL_REQUEST_NUMBER is $PULL_REQUEST_NUMBER"
        env:
          BOT_URL: ${{ secrets.BOT_URL }}
          PULL_REQUEST_NUMBER: ${{ steps.pr.outputs.id }}

  # Build failed, update comment
  on-failure:
    name: Build failed
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Download pr number
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: pr

      - name: Output pr number
        id: pr
        run: echo "::set-output name=id::$(<pr.txt)"

      - name: Update comment
        run: |
          echo "PULL_REQUEST_NUMBER is $PULL_REQUEST_NUMBER"
        env:
          BOT_URL: ${{ secrets.BOT_URL }}
          PULL_REQUEST_NUMBER: ${{ steps.pr.outputs.id }}
